services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: workout
      DB_PASSWORD: workout
      DB_NAME: workout
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "5433:5433"
volumes:
  postgres_data:
